# Generated by Django 3.1.7 on 2022-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('comname', models.CharField(max_length=150)),
                ('comowner', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('shoplicense', models.ImageField(blank=True, null=True, upload_to='shoplicense/')),
                ('fssai', models.ImageField(blank=True, null=True, upload_to='fssai/')),
                ('gsti_pan', models.ImageField(blank=True, null=True, upload_to='gsti_pan/')),
            ],
        ),
    ]
