# Generated by Django 3.1.7 on 2021-11-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='planname',
            new_name='planowner',
        ),
    ]
