# Generated by Django 3.1.7 on 2021-11-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211129_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.TextField()),
                ('mobno', models.CharField(editable=False, max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('plansubscribed', models.IntegerField()),
                ('payment', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
