# Generated by Django 3.1.7 on 2021-11-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
