# Generated by Django 3.2.4 on 2021-11-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobno', models.CharField(editable=False, max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
