# Generated by Django 3.2.4 on 2021-11-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='mobno',
            new_name='mobile',
        ),
    ]
