# Generated by Django 3.2.4 on 2021-11-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_feedback_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='mobno',
            field=models.CharField(max_length=10),
        ),
    ]
